#!/bin/bash
# -*- coding: UTF-8 -*-

# Script for building boost libraries for Linux, OSX, iOS and Android.


### Define text styles  ###########
TXT_C="tput setaf"    # set text color in BGR format
TXT_R="tput sgr0"     # reset text format
TXT_B="tput bold"     # set bold
TXT_U="tput sgr 0 1"  # set underlined


# Detect directory in which the script resides
BASEDIR=$(dirname "`[[ $0 == /* ]] && echo "$0" || echo "${PWD}/${0#./}"`")

# Define output directory if not defined yet
[ -z "$STAGING_PREFIX" ] && STAGING_PREFIX=$BASEDIR/../../../../hookflash-staging
UNAME=$(uname)

validate_before(){
    [ $? != "0" ] && exit 1 || true
}


caption(){
	echo -e "\n`$TXT_B`Build script`$TXT_R` for building `$TXT_B`boost`$TXT_R` libraries for multiple platforms."
	echo -e "Maintainer: `$TXT_B`Predrag Mandic`$TXT_R` [`$TXT_U``$TXT_C 4`predrag@hookflash.com`$TXT_R`]`$TXT_R`"
}

help_darwin(){
	caption
	usage_darwin
	echo -e "`$TXT_B`\nOptions`$TXT_R`"
	echo -e "\t`$TXT_B`x86`$TXT_R` | x86_64 | i386"
	echo -e "\t\tAll of these options build the same libraries that work on OS X on a current processor architecture (32 or 64 bit). They exist separately to solve legacy issues."
	echo -e "\t`$TXT_B`arm`$TXT_R` | ios"
	echo -e "\t\tBoth of these options build the same libraries that work on iOS. They exist separately to solve legacy issues."
	echo -e "\t`$TXT_B`all`$TXT_R`"
	echo -e "\t\tBuilds both x86 and ios libraries."
	echo -e "\t`$TXT_B`clean`$TXT_R`"
	echo -e "\t\tDeletes staged libraries for all architectures."
	echo ""
}

usage_darwin(){
	echo "Usage: build {arm|x86|all|clean|help}"
}

usage_darwin_clean(){
	echo "Usage: build clean {arm|x86|all}"
}

help_linux(){
	caption
	usage_linux
	echo -e "`$TXT_B`\nOptions`$TXT_R`"
	echo -e "\t`$TXT_B`x86`$TXT_R` | x86_64 | i386"
	echo -e "\t\tAll of these options build the same libraries that work on Linux on a current processor architecture (32 or 64 bit). They exist separately to solve legacy issues."
	echo -e "\t`$TXT_B`arm`$TXT_R` | android"
	echo -e "\t\tBoth of these options build the same libraries that work on Android. They exist separately to solve legacy issues."
	echo -e "\t`$TXT_B`all`$TXT_R`"
	echo -e "\t\tBuilds both x86 and android libraries."
	echo -e "\t`$TXT_B`clean`$TXT_R`"
	echo -e "\t\tDeletes staged libraries for all architectures."
	echo ""
}

usage_linux(){
	echo "Usage: build {arm|x86|all|clean|help}"
}

usage_linux_clean(){
	echo "Usage: build clean {arm|x86|all}"
}

build_darwin(){
	echo "`$TXT_B``$TXT_C 2`boost build for OS X started...`$TXT_R`"

	pushd $BASEDIR/../../boost
	
	#removing old user-config.jam
	touch ~/user-config.jam
	rm -f ~/user-config.jam; validate_before
	
	./bootstrap.sh --with-libraries=thread,date_time,regex ; validate_before
	./bjam clean; validate_before
	./bjam --prefix=$STAGING_PREFIX architecture=x86 address-model=32 link=static install ; validate_before
	
	popd
}

clean_darwin(){
	echo "Cleaning OSX architecture..."
	rm -rf $STAGING_PREFIX/include/boost
	rm -f $STAGING_PREFIX/lib/libboost_*
	echo "Done!"
}

build_ios(){
	xcode_version=`system_profiler SPDeveloperToolsDataType | grep -B 1 Xcode.app | grep -v Xcode.app | grep -v -- -- | awk 'NR==1 {print $2}'`
	DEVELOPER=`xcode-select -print-path`
	COMPILER=$DEVELOPER/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc
	ARCH=armv7
	IOS_PREFIX=$STAGING_PREFIX/iPhoneOS
	
	TOOLS="tools"
	CONVERT="armv7s_convert"
	CONVERT_SCRIPT="convert_armv7_to_armv7s.sh"
	
	mkdir -p $IOS_PREFIX
	echo "`$TXT_B``$TXT_C 2`boost build for iOS started...`$TXT_R`"
	
	pushd $BASEDIR/../../boost
		#creating user-config.jam
		touch ~/user-config.jam
		rm ~/user-config.jam
		touch ~/user-config.jam
		echo """using darwin
: $xcode_version~iphone
: $COMPILER
: <striper> <compileflags>-mthumb <compileflags>-fvisibility=hidden <compileflags>-fvisibility-inlines-hidden <compileflags>-D_LITTLE_ENDIAN
: <architecture>arm <target-os>iphone
;
""" > ~/user-config.jam ; validate_before
# <compileflags>-arch $ARCH  
	
		./bootstrap.sh --with-libraries=thread,date_time,regex ; validate_before
		./bjam --prefix=$IOS_PREFIX toolset=darwin cflags="-fvisibility=default -fvisibility-inlines-hidden -mthumb -arch $ARCH" architecture=arm target-os=iphone macosx-version=iphone-6.1 link=static threading=multi define=_LITTLE_ENDIAN install
		rm ~/user-config.jam
	popd
	
	pushd $TOOLS
		clang -o $CONVERT $CONVERT.c
		mv $CONVERT $IOS_PREFIX/lib/$CONVERT
		cp $CONVERT_SCRIPT $IOS_PREFIX/lib/$CONVERT_SCRIPT
	popd
	
	pushd $IOS_PREFIX/lib
		./$CONVERT_SCRIPT libboost_date_time.a
		./$CONVERT_SCRIPT libboost_regex.a
		./$CONVERT_SCRIPT libboost_system.a
		./$CONVERT_SCRIPT libboost_thread.a
		rm $CONVERT_SCRIPT
		rm ./$CONVERT
	popd
}

clean_ios(){
	echo "Cleaning iOS architecture..."
	rm -rf $STAGING_PREFIX/iPhoneOS/include/boost
	rm -f $STAGING_PREFIX/iPhoneOS/lib/libboost_*
	echo "Done!"
}

build_linux(){
	echo "`$TXT_B``$TXT_C 2`boost build for Linux started...`$TXT_R`"
	mkdir -p $STAGING_PREFIX; validate_before

	cd $BASEDIR/../../boost
	./bootstrap.sh --with-libraries=thread,date_time ; validate_before
	./bjam clean; validate_before
	./bjam --prefix=$STAGING_PREFIX cxxflags=-fPIC link=static install; validate_before
}

clean_linux(){
	echo "Cleaning Linux architecture..."
	rm -rf $STAGING_PREFIX/include/boost
	rm -f $STAGING_PREFIX/lib/libboost_*
	echo "Done!"
}

build_android(){
	echo -e "`$TXT_C 1`Android build is not working. Use help or contact maintainer for info.`$TXT_R`"
	exit 1
}

clean_android(){
	echo "Cleaning Android architecture..."
	echo -e "`$TXT_C 1`Android clean is not working. Use help or contact maintainer for info.`$TXT_R`"
	exit 1
}


case "$UNAME" in
	Linux)
		case "$1" in
			arm|android)
				build_android
				;;
			x86|x86_64|i386)
				build_linux
				;;
			all)
				build_linux
				build_android
				;;
			clean)
				case "$2" in
					x86|x86_64|i386)
					clean_linux
					;;
				arm|android)
					clean_android
					;;
				all)
					clean_linux
					clean_android
					;;
				*)
					usage_linux_clean
					exit 1
					;;
				esac
				;;
			help)
				help_linux
				;;
			*)
				usage_linux
				exit 1
				;;
		esac
		;;

	Darwin)
		case "$1" in
			arm|ios)
				build_ios
				;;
			x86|x86_64|i386|osx)
				build_darwin
				;;
			all)
				build_darwin
				build_ios
				;;
			clean)
				case "$2" in
					x86|x86_64|i386|osx)
					clean_darwin
					;;
				arm|ios)
					clean_ios
					;;
				all)
					clean_darwin
					clean_ios
					;;
				*)
					clean_darwin
					clean_ios
					#usage_darwin_clean
					#exit 1
					;;
				esac
				;;
			help)
				help_darwin
				;;
			*)
				build_darwin
				build_ios
				#usage_darwin
				#exit 1
				;;
		esac
		;;
	*)
		echo "`$TXT_B`$UNAME`$TXT_R`: `$TXT_C 1`operating system not supported`$TXT_R`"
		exit 1
		;;
esac

