#!/bin/bash
# -*- coding: UTF-8 -*-

# Script for building curl library for multiple platforms.


### Define text styles  ###########
TXT_C="tput setaf"    # set text color in BGR format
TXT_R="tput sgr0"     # reset text format
TXT_B="tput bold"     # set bold
TXT_U="tput sgr 0 1"  # set underlined

# Detect directory in which the script resides
BASEDIR=$(dirname "`[[ $0 == /* ]] && echo "$0" || echo "${PWD}/${0#./}"`")

# Define output directory if not defined yet
[ -z "$STAGING_PREFIX" ] && STAGING_PREFIX=$BASEDIR/../../../../hookflash-staging

# Detect OS
UNAME=$(uname)

validate_before(){
    [ $? != "0" ] && exit 1 || true
}


caption(){
	echo -e "\n`$TXT_B`Build script`$TXT_R` for building `$TXT_B`curl`$TXT_R` library for multiple platforms."
	echo -e "Maintainer: `$TXT_B`Predrag Mandic`$TXT_R` [`$TXT_U``$TXT_C 4`predrag@hookflash.com`$TXT_R`]`$TXT_R`"
}

help_darwin(){
	caption
	usage_darwin
	echo -e "`$TXT_B`\nOptions`$TXT_R`"
	echo -e "\t`$TXT_B`x86`$TXT_R` | x86_64 | i386"
	echo -e "\t\tAll of these options build the same libraries that work on OS X on a current processor architecture (32 or 64 bit). They exist separately to solve legacy issues."
	echo -e "\t`$TXT_B`arm`$TXT_R` | ios"
	echo -e "\t\tBoth of these options build the same libraries that work on iOS. They exist separately to solve legacy issues."
	echo -e "\t`$TXT_B`all`$TXT_R`"
	echo -e "\t\tBuilds both x86 and ios libraries."
	echo -e "\t`$TXT_B`clean`$TXT_R`"
	echo -e "\t\tDeletes staged libraries for all architectures."
	echo ""
}

usage_darwin(){
	echo "Usage: build {arm|x86|all|clean|help}"
}

help_linux(){
	caption
	usage_linux
	echo -e "`$TXT_B`\nOptions`$TXT_R`"
	echo -e "\t`$TXT_B`x86`$TXT_R` | x86_64 | i386"
	echo -e "\t\tAll of these options build the same libraries that work on Linux on a current processor architecture (32 or 64 bit). They exist separately to solve legacy issues."
	echo -e "\t`$TXT_B`arm`$TXT_R` | android"
	echo -e "\t\tBoth of these options build the same libraries that work on Android. They exist separately to solve legacy issues."
	echo -e "\t`$TXT_B`all`$TXT_R`"
	echo -e "\t\tBuilds both x86 and android libraries."
	echo -e "\t`$TXT_B`clean`$TXT_R`"
	echo -e "\t\tDeletes staged libraries for all architectures."
	echo ""
}

usage_linux(){
	echo "Usage: build {arm|x86|all|clean|help}"
}

build_darwin(){
	echo "`$TXT_B``$TXT_C 2`curl build for OS X started...`$TXT_R`"
	mkdir -p $STAGING_PREFIX; validate_before
	cd $BASEDIR/../../curl
		cp include/curl/curlbuild.h.template include/curl/curlbuild.h
		cat Makefile.template > Makefile; validate_before
        CFLAGS="-m32" ./configure --disable-ftp --disable-file --disable-ldap --disable-dict --disable-telnet --disable-tftp --disable-rtsp --disable-pop3 --disable-imap --disable-smtp --disable-gopher --disable-debug --without-ssl --without-zlib --without-libidn --enable-static=yes --enable-shared=no ; validate_before
        make; validate_before
		make install prefix=$STAGING_PREFIX; validate_before
		rm Makefile
    cd -
}

build_ios(){
	echo "`$TXT_B``$TXT_C 2`curl build for iOS started...`$TXT_R`"
		cd $BASEDIR/../../curl
		cp include/curl/curlbuild.h.template include/curl/curlbuild.h
		cd -
	
	set -e
	#export CURL_VERSION="7.22.0"
	export PLATFORM="iPhoneOS"
	export SDK="6.0"
	export ARCH="armv7"
	
	export DEVELOPER="/Applications/Xcode.app/Contents/Developer"
	export DEVROOT="${DEVELOPER}/Platforms/${PLATFORM}.platform/Developer"
	export SDKROOT="${DEVROOT}/SDKs/${PLATFORM}${SDK}.sdk"
	export CC=${DEVROOT}/usr/bin/gcc
	export LD=${DEVROOT}/usr/bin/ld
	export CPP=${DEVELOPER}/usr/bin/cpp
	export CXX=${DEVROOT}/usr/bin/g++
	unset AR
	unset AS
	export NM=${DEVROOT}/usr/bin/nm
	export CXXCPP=${DEVELOPER}/usr/bin/cpp
	export RANLIB=${DEVROOT}/usr/bin/ranlib
	export LDFLAGS="-arch ${ARCH} -pipe -no-cpp-precomp -isysroot ${SDKROOT} -L${ROOTDIR}/lib"
	export CFLAGS="-arch ${ARCH} -pipe -no-cpp-precomp -isysroot ${SDKROOT} -I${ROOTDIR}/include"
	export CXXFLAGS="-arch ${ARCH} -pipe -no-cpp-precomp -isysroot ${SDKROOT} -I${ROOTDIR}/include"
	
	#pushd "../../curl-${CURL_VERSION}"
	pushd "../../curl"
	
	
	rm -rf "${ARCH}"
	mkdir -p "${ARCH}"
	pushd "${ARCH}"
	
	export ROOTDIR=`pwd`
	
	pushd "../"
	
	mkdir -p $STAGING_PREFIX/iPhoneOS
	cat $BASEDIR/../../curl/Makefile.template > $BASEDIR/../../curl/Makefile

	./configure --host=${ARCH}-apple-darwin --prefix=$STAGING_PREFIX/iPhoneOS --without-ssl --without-libssh2 --with-random=/dev/urandom --disable-shared --enable-static --disable-ipv6 --disable-manual --disable-verbose ; validate_before
	
	pushd "lib"
	make; validate_before
	make install; validate_before
	popd
	pushd "include"
	make ; validate_before
	make install ; validate_before
	popd
	popd

	rm $BASEDIR/../../curl/Makefile


	### LEGACY PROBLEM FIX ###################
	cd "$STAGING_PREFIX"
		rm -rf iPhoneOS5.0
		ln -s iPhoneOS iPhoneOS5.0
		rm -rf iPhoneOS5.1
		ln -s iPhoneOS iPhoneOS5.1
		rm -rf iPhoneOS6.0
		ln -s iPhoneOS iPhoneOS6.0
	cd -
}

clean_darwin(){
	echo -e "`$TXT_C 1`This option is not implemented. Use help or contact maintainer for info.`$TXT_R`"
	exit 1
	#TODO
}

build_linux(){
	echo "`$TXT_B``$TXT_C 2`curl build for Linux started...`$TXT_R`"
	mkdir -p $STAGING_PREFIX; validate_before
	cd $BASEDIR/../../curl
		cp include/curl/curlbuild.h.template include/curl/curlbuild.h
        cat Makefile.template > Makefile; validate_before
        ./configure --disable-ftp --disable-file --disable-ldap --disable-dict --disable-telnet --disable-tftp --disable-rtsp --disable-pop3 --disable-imap --disable-smtp --disable-gopher --disable-debug --without-ssl --without-zlib --without-libidn ; validate_before
        make ; validate_before
        make install prefix=$STAGING_PREFIX; validate_before
		rm Makefile
    cd -
}

build_android(){
	echo -e "`$TXT_C 1`This option is not implemented. Use help or contact maintainer for info.`$TXT_R`"
		#cp include/curl/curlbuild.h.template include/curl/curlbuild.h
		#TODO: When implementing, don't forget the line above! ^^^
	exit 1
	#mkdir -p $STAGING_PREFIX
	#TODO
}

clean_linux(){
	echo -e "`$TXT_C 1`This option is not implemented. Use help or contact maintainer for info.`$TXT_R`"
	exit 1
	#TODO
}


case "$UNAME" in
	Linux)
		case "$1" in
			arm|android)
				build_android
				;;
			x86|x86_64|i386)
				build_linux
				;;
			all)
				build_linux
				build_android
				;;
			clean)
				clean_linux
				;;
			help)
				help_linux
				;;
			*)
				usage_linux
				exit 1
				;;
		esac
		;;

	Darwin)
		case "$1" in
			arm|ios)
				build_ios
				;;
			x86|x86_64|i386|osx)
				build_darwin
				;;
			all)
				build_darwin
				build_ios
				;;
			clean)
				clean_darwin
				;;
			help)
				help_darwin
				;;
			*)
				usage_darwin
				exit 1
				;;
		esac
		;;
	*)
		echo "`$TXT_B`$UNAME`$TXT_R`: `$TXT_C 1`operating system not supported`$TXT_R`"
		exit 1
		;;
esac

