# This file is generated by gyp; do not edit.

export builddir_name ?= trunk/webrtc/voice_engine/out
.PHONY: all
all:
	$(MAKE) -C ../.. voice_engine_core voe_auto_test voe_cmd_test voice_engine_unittests
