# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := audio_processing_offsets
### Generated for rule trunk_webrtc_modules_modules_gyp_audio_processing_offsets_target_generate_asm_header:
$(obj)/gen/audio_processing/asm_offsets/aecm_core_neon_offsets.h: obj := $(abs_obj)
$(obj)/gen/audio_processing/asm_offsets/aecm_core_neon_offsets.h: builddir := $(abs_builddir)
$(obj)/gen/audio_processing/asm_offsets/aecm_core_neon_offsets.h: TOOLSET := $(TOOLSET)
$(obj)/gen/audio_processing/asm_offsets/aecm_core_neon_offsets.h: webrtc/modules/audio_processing/aecm/aecm_core_neon_offsets.c webrtc/build/generate_asm_header.py FORCE_DO_CMD
	$(call do_cmd,trunk_webrtc_modules_modules_gyp_audio_processing_offsets_target_generate_asm_header_0)

all_deps += $(obj)/gen/audio_processing/asm_offsets/aecm_core_neon_offsets.h
cmd_trunk_webrtc_modules_modules_gyp_audio_processing_offsets_target_generate_asm_header_0 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd webrtc/modules; mkdir -p $(obj)/gen/audio_processing/asm_offsets; python ../../webrtc/build/generate_asm_header.py "--compiler=$(ANDROID_NDK_PATH)/toolchains/arm-linux-androideabi-4.6/prebuilt/$(PLATFORM)/bin/arm-linux-androideabi-gcc" "--options=-I../../webrtc/.. -I$(ANDROID_NDK_PATH)/platforms/android-9/arch-arm/usr/include -S" "--pattern=offset_" "--dir=$(obj)/gen/audio_processing/asm_offsets" "$(abspath $<)"
quiet_cmd_trunk_webrtc_modules_modules_gyp_audio_processing_offsets_target_generate_asm_header_0 = RULE trunk_webrtc_modules_modules_gyp_audio_processing_offsets_target_generate_asm_header_0 $@

$(obj)/gen/audio_processing/asm_offsets/nsx_core_neon_offsets.h: obj := $(abs_obj)
$(obj)/gen/audio_processing/asm_offsets/nsx_core_neon_offsets.h: builddir := $(abs_builddir)
$(obj)/gen/audio_processing/asm_offsets/nsx_core_neon_offsets.h: TOOLSET := $(TOOLSET)
$(obj)/gen/audio_processing/asm_offsets/nsx_core_neon_offsets.h: webrtc/modules/audio_processing/ns/nsx_core_neon_offsets.c webrtc/build/generate_asm_header.py FORCE_DO_CMD
	$(call do_cmd,trunk_webrtc_modules_modules_gyp_audio_processing_offsets_target_generate_asm_header_1)

all_deps += $(obj)/gen/audio_processing/asm_offsets/nsx_core_neon_offsets.h
cmd_trunk_webrtc_modules_modules_gyp_audio_processing_offsets_target_generate_asm_header_1 = LD_LIBRARY_PATH=$(builddir)/lib.host:$(builddir)/lib.target:$$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd webrtc/modules; mkdir -p $(obj)/gen/audio_processing/asm_offsets; python ../../webrtc/build/generate_asm_header.py "--compiler=$(ANDROID_NDK_PATH)/toolchains/arm-linux-androideabi-4.6/prebuilt/$(PLATFORM)/bin/arm-linux-androideabi-gcc" "--options=-I../../webrtc/.. -I$(ANDROID_NDK_PATH)/platforms/android-9/arch-arm/usr/include -S" "--pattern=offset_" "--dir=$(obj)/gen/audio_processing/asm_offsets" "$(abspath $<)"
quiet_cmd_trunk_webrtc_modules_modules_gyp_audio_processing_offsets_target_generate_asm_header_1 = RULE trunk_webrtc_modules_modules_gyp_audio_processing_offsets_target_generate_asm_header_1 $@

rule_trunk_webrtc_modules_modules_gyp_audio_processing_offsets_target_generate_asm_header_outputs := \
	$(obj)/gen/audio_processing/asm_offsets/aecm_core_neon_offsets.h \
	$(obj)/gen/audio_processing/asm_offsets/nsx_core_neon_offsets.h

### Finished generating for rule: trunk_webrtc_modules_modules_gyp_audio_processing_offsets_target_generate_asm_header

### Finished generating for all rules

DEFS_Debug := \
	'-DWEBRTC_SVNREVISION="Unavailable(issue687)"' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DUSE_LINUX_BREAKPAD' \
	'-DNO_TCMALLOC' \
	'-DDISABLE_NACL' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DENABLE_WEBRTC=1' \
	'-DUSE_PROPRIETARY_CODECS' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_GPU=1' \
	'-DUSE_OPENSSL=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DWEBRTC_LOGGING' \
	'-DWEBRTC_ARCH_ARM' \
	'-DWEBRTC_ARCH_ARM_V7' \
	'-DWEBRTC_DETECT_ARM_NEON' \
	'-DWEBRTC_LINUX' \
	'-DWEBRTC_ANDROID' \
	'-DWEBRTC_CLOCK_TYPE_REALTIME' \
	'-DWEBRTC_THREAD_RR' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DANDROID' \
	'-D__GNU_SOURCE=1' \
	'-DUSE_STLPORT=1' \
	'-D_STLP_USE_PTR_SPECIALIZATIONS=1' \
	'-DCHROME_BUILD_ID=""' \
	'-DHAVE_SYS_UIO_H' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wextra \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fno-builtin-cos \
	-fno-builtin-sin \
	-fno-builtin-cosf \
	-fno-builtin-sinf \
	-mthumb \
	-march=armv7-a \
	-mtune=cortex-a8 \
	-mfloat-abi=softfp \
	-mfpu=vfpv3-d16 \
	-fno-tree-sra \
	-fuse-ld=gold \
	-Wno-psabi \
	-mthumb-interwork \
	-ffunction-sections \
	-funwind-tables \
	-g \
	-fstack-protector \
	-fno-short-enums \
	-finline-limit=64 \
	-Wa,--noexecstack \
	--sysroot=$(ANDROID_NDK_PATH)/platforms/android-9/arch-arm \
	-I$(ANDROID_NDK_PATH)/sources/cxx-stl/stlport/stlport \
	-I$(ANDROID_NDK_PATH)/sources/cxx-stl/gnu-libstdc++/4.6/include \
	-Os \
	-g \
	-fomit-frame-pointer \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare \
	-Woverloaded-virtual \
	-Wno-abi

INCS_Debug := \
	-Iwebrtc \
	-I. \
	-I.

DEFS_Release := \
	'-DWEBRTC_SVNREVISION="Unavailable(issue687)"' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DUSE_LINUX_BREAKPAD' \
	'-DNO_TCMALLOC' \
	'-DDISABLE_NACL' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DENABLE_WEBRTC=1' \
	'-DUSE_PROPRIETARY_CODECS' \
	'-DENABLE_PEPPER_THREADING' \
	'-DENABLE_GPU=1' \
	'-DUSE_OPENSSL=1' \
	'-DENABLE_EGLIMAGE=1' \
	'-DUSE_SKIA=1' \
	'-DWEBRTC_LOGGING' \
	'-DWEBRTC_ARCH_ARM' \
	'-DWEBRTC_ARCH_ARM_V7' \
	'-DWEBRTC_DETECT_ARM_NEON' \
	'-DWEBRTC_LINUX' \
	'-DWEBRTC_ANDROID' \
	'-DWEBRTC_CLOCK_TYPE_REALTIME' \
	'-DWEBRTC_THREAD_RR' \
	'-D__STDC_CONSTANT_MACROS' \
	'-D__STDC_FORMAT_MACROS' \
	'-DANDROID' \
	'-D__GNU_SOURCE=1' \
	'-DUSE_STLPORT=1' \
	'-D_STLP_USE_PTR_SPECIALIZATIONS=1' \
	'-DCHROME_BUILD_ID=""' \
	'-DHAVE_SYS_UIO_H' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0' \
	'-D_FORTIFY_SOURCE=2'

# Flags passed to all source files.
CFLAGS_Release := \
	-fstack-protector \
	--param=ssp-buffer-size=4 \
	-Werror \
	-fno-exceptions \
	-fno-strict-aliasing \
	-Wall \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wextra \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fno-builtin-cos \
	-fno-builtin-sin \
	-fno-builtin-cosf \
	-fno-builtin-sinf \
	-mthumb \
	-march=armv7-a \
	-mtune=cortex-a8 \
	-mfloat-abi=softfp \
	-mfpu=vfpv3-d16 \
	-fno-tree-sra \
	-fuse-ld=gold \
	-Wno-psabi \
	-mthumb-interwork \
	-ffunction-sections \
	-funwind-tables \
	-g \
	-fstack-protector \
	-fno-short-enums \
	-finline-limit=64 \
	-Wa,--noexecstack \
	--sysroot=$(ANDROID_NDK_PATH)/platforms/android-9/arch-arm \
	-I$(ANDROID_NDK_PATH)/sources/cxx-stl/stlport/stlport \
	-I$(ANDROID_NDK_PATH)/sources/cxx-stl/gnu-libstdc++/4.6/include \
	-Os \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections \
	-fomit-frame-pointer

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wsign-compare \
	-Woverloaded-virtual \
	-Wno-abi

INCS_Release := \
	-Iwebrtc \
	-I. \
	-I.

OBJS := \
	$(obj).target/$(TARGET)/webrtc/modules/audio_processing/aecm/aecm_core_neon_offsets.o \
	$(obj).target/$(TARGET)/webrtc/modules/audio_processing/ns/nsx_core_neon_offsets.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our actions/rules run before any of us.
$(OBJS): | $(rule_trunk_webrtc_modules_modules_gyp_audio_processing_offsets_target_generate_asm_header_outputs)

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
# Build our special outputs first.
$(obj).target/webrtc/modules/audio_processing_offsets.stamp: | $(rule_trunk_webrtc_modules_modules_gyp_audio_processing_offsets_target_generate_asm_header_outputs)

# Preserve order dependency of special output on deps.
$(rule_trunk_webrtc_modules_modules_gyp_audio_processing_offsets_target_generate_asm_header_outputs): | 

$(obj).target/webrtc/modules/audio_processing_offsets.stamp: TOOLSET := $(TOOLSET)
$(obj).target/webrtc/modules/audio_processing_offsets.stamp:  FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/webrtc/modules/audio_processing_offsets.stamp
# Add target alias
.PHONY: audio_processing_offsets
audio_processing_offsets: $(obj).target/webrtc/modules/audio_processing_offsets.stamp

# Add target alias to "all" target.
.PHONY: all
all: audio_processing_offsets

