# This file is generated by gyp; do not edit.

export builddir_name ?= trunk/webrtc/video_engine/out
.PHONY: all
all:
	$(MAKE) -C ../.. video_engine_core libvietest video_engine_core_unittests video_demo_apk libvietest_unittests vie_auto_test
