#!/bin/sh
# -*- coding: UTF-8 -*-

# Script for building openpeerstack static library on linux.

BASEDIR=$(dirname $0)
if [ $BASEDIR = '.' ]; then BASEDIR=`pwd`; fi


if [ `uname` != 'Linux' ]; then
   printf "Linux not detected.\nexiting script...\n"
else
	mkdir -p $BASEDIR/out
	rm -rf $BASEDIR/out/*

	cd $BASEDIR

		echo "\nBuilding openpeerstack message objects..." 2>&1 | tee $BASEDIR/build-openpeerstack.log
		echo "----------------------------------------" 2>&1 | tee -a $BASEDIR/build-openpeerstack.log
		make -f $BASEDIR/Makefile-openpeerstackmessage 2>&1 | tee -a $BASEDIR/build-openpeerstack.log

		echo "\nBuilding openpeerstack..." 2>&1 | tee $BASEDIR/build-openpeerstack.log
		echo "----------------------------------------" 2>&1 | tee -a $BASEDIR/build-openpeerstack.log
		make -f $BASEDIR/Makefile-openpeerstack 2>&1 | tee -a $BASEDIR/build-openpeerstack.log

		#echo "\nBuilding zsLib test" 2>&1 | tee -a $BASEDIR/build-openpeerstack.log
		#echo "----------------------------------------" 2>&1 | tee -a $BASEDIR/build-openpeerstack.log
		#make -f Makefile-test 2>&1 | tee -a $BASEDIR/build-openpeerstack.log
		
	cd -
fi

