# This file is generated by gyp; do not edit.

export builddir_name ?= trunk/webrtc/modules/video_coding/codecs/vp8/out
.PHONY: all
all:
	$(MAKE) -C ../../../../.. webrtc_vp8 test_framework vp8_integrationtests vp8_unittests vp8_coder
